### ISSUE TITLE
Front page links only take you the start of a discussion

### ISSUE THREAD

**Issue by BiggerRob** [brainwipe/lack-of#4]
When a discussion gets long, it can spread over many pages, but clicking the link on the home page only takes you the first page of the discussion, requiring the user to page through to the new comments ... but viewing the first page marks the unread comments as read, so by the time you get to them they no longer have clear markers to show which are new.

**Comment by brainwipe** [comment]
Would it be a good idea to make the pages scroll infinitely? I kind of hate paging these days.

**Comment by BiggerRob** [comment]
Perhaps.
Maybe ripoff Facebook and have the comments listed newest first?
Maybe make the page size much larger, or (again ripping off Facebook) load them as you scroll down.

**Comment by brainwipe** [comment]
Have you tried clicking on the red number on the right?

**Comment by BiggerRob** [comment]
I am going to admit that I have not, but I will keep an eye out for an opportunity in the future on a suitably long post.

**Comment by BiggerRob** [comment]
Point made, closing this issue specific (training issue).
Feel free to spawn the feature request to remove paging to a new issue.
