### ISSUE TITLE
Could use a search feature

### ISSUE THREAD

**Issue by BiggerRob** [brainwipe/lack-of#6]
It has only been an issue once or twice for me but when I had to find an old post for reference, it can take a very long time to page ... and page ... and page ... and page to find what you are after.

**Comment by brainwipe** [comment]
Agreed. I think this is a matter of working out where to put the sodding search box!

**Comment by brainwipe** [comment]
We have a page you can go to in the meantime but I agree that it should be more front and centre.
http://www.lack-of.org/search/node

**Comment by brainwipe** [comment]
Implemented as config
